### ISSUE TITLE
Error in loading packages for create_shapefile

### ISSUE THREAD

**Issue by jeffreydemieville** [phytooracle/phenotype_extraction_update#2]
Received below error when attempting to load rgdal package in create_shapefile:
```
> library(rgdal)
Error in library(rgdal) : there is no package called ‘rgdal’
> install.packages(c('rgdal'))
Installing package into ‘C:/Users/jdemieville/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘rgdal’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

Attempted to install package manually and it is not available for this version of R. 

Default version of R used by Rstudio on lab workstation is 4.3.1 (2023-06-16 ucrt).

**Comment by jeffreydemieville** [comment]
Per https://cran.r-project.org/web/packages/rgdal/index.html

"Package ‘rgdal’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/rgdal).

Archived on 2023-10-16 at the request of the maintainer. Consider using 'sf' or 'terra' instead.

A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2023/2023-10-16_check_results_rgdal.html).

Please use the canonical form https://cran.r-project.org/package=rgdal to link to this page."

**Comment by emmanuelgonz** [comment]
Issue has been resolved by commenting out "rgdal" and "rgeos": https://github.com/phytooracle/phenotype_extraction_update/commit/e290a9965ceb6b0e4e39699fa3ffa36c08fc8f45
